import Head from 'next/head'
import { motion } from "framer-motion"
import withTransition from "../HOC/withTransition";
import OpenseaList from '../components/opensea/OpenseaList';
import Banner from '../components/partials/Banner';
import Header from '../components/partials/Header';

function Home() {
  return (

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Banner />

      <div className="relative py-20">
        <div className="absolute top-0 left-0 z--1 w-full h-full overflow-hidden">
          <img src="./circle-doodle-bg.png" className="w-full opacity-20" />
        </div>
        <div className="container grid md:grid-cols-3 gap-4">
          <motion.div
            whileInView="visible"
            viewport={{ once: true }}
            initial="hidden"
            variants={{
              visible: { opacity: 1, y: 0 },
              hidden: { opacity: 0, y: 20 }
            }}
            transition={{ duration: 1 }}
            className="rounded bg-yellow-50 relative h-80 group cursor-pointer">
            <div className="absolute top-0 w-full h-full overflow-hidden rounded">
              <div className="bg-blend-multiply bg-gray-500 absolute h-full w-full top-0 opacity-40 rounded z-10"></div>
              <img src="https://images.unsplash.com/photo-1566235514140-af6ae28a8971?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80" className="h-full w-full object-cover rounded group-hover:scale-110 transition" />
            </div>
            <div className="absolute bottom-0 px-4 py-6 text-white w-full z-20 h-40 flex flex-col justify-between">
              <div>
                <h3 className="text-3xl">Photography</h3>
                <p>Take stunning images with your smart phone.</p>
              </div>
              <a className="text-sm font-bold cursor-pointer group-hover:underline">Find out more →</a>
            </div>
          </motion.div>
          <div className="rounded bg-yellow-50 relative h-80 group cursor-pointer">
            <div className="absolute top-0 w-full h-full overflow-hidden rounded">
              <div className="bg-blend-multiply bg-gray-500 absolute h-full w-full top-0 opacity-40 rounded z-10"></div>
              <img src="https://images.unsplash.com/photo-1640340434868-6877662a809f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80" className="h-full w-full object-cover rounded group-hover:scale-110 transition" />
            </div>
            <div className="absolute bottom-0 px-4 py-6 text-white w-full z-20 h-40 flex flex-col justify-between">
              <div>
                <h3 className="text-3xl">NFTs</h3>
                <p>Share your 1/1s or collections artwork with collectors.</p>
              </div>
              <a className="text-sm font-bold cursor-pointer group-hover:underline">Find out more →</a>
            </div>
          </div>
          <div className="rounded bg-yellow-50 relative h-80 group cursor-pointer">
            <div className="absolute top-0 w-full h-full overflow-hidden rounded">
              <div className="bg-blend-multiply bg-gray-500 absolute h-full w-full top-0 opacity-40 rounded z-10"></div>
              <img src="https://images.unsplash.com/photo-1610737249253-1405407a33ad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" className="h-full w-full object-cover rounded group-hover:scale-110 transition" />
            </div>
            <div className="absolute bottom-0 px-4 py-6 text-white w-full z-20 h-40 flex flex-col justify-between">
              <div>
                <h3 className="text-3xl">Podcasts</h3>
                <p>Listen to news and opinions</p>
              </div>
              <a className="text-sm font-bold cursor-pointer group-hover:underline">Find out more →</a>
            </div>
          </div>
        </div>

      </div>


      <div className="py-20 bg-gray-100">

        <OpenseaList assetView={false} />

      </div>


      <div className="py-20 bg-gray-200">

        <OpenseaList assetView={true} />

      </div>



      <div className="container md:flex py-20">

        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1 },
            hidden: { opacity: 0 }
          }}
          className="flex-1 text-gray-700 text-center bg-gray-400 p-5 m-2 rounded">
          <div className="md:flex md:items-center">
            <div className="md:flex-shrink-0">
              <img src="./vercel.svg" className="rounded-lg lg:w-64" />
            </div>
            <div className="mt-4 md:mt-0 md:ml-6">
              <div className="uppercase tracking-wide text-sm text-indigo-600 font-bold">Blockchain</div>
              <a className="block mt-1 text-lg leading-tight font-semibold text-gray-900 hover:underline cursor-pointer">Finding connections to help decentralisation</a>
            </div>
          </div>
        </motion.div>

        <div className="flex-1 text-gray-700 text-center bg-gray-400 p-5 m-2 rounded">
          <div className="md:flex md:items-center">
            <div className="md:flex-shrink-0">
              <img src="./vercel.svg" className="rounded-lg lg:w-64" />
            </div>
            <div className="mt-4 md:mt-0 md:ml-6">
              <div className="uppercase tracking-wide text-sm text-indigo-600 font-bold">Blockchain</div>
              <a className="block mt-1 text-lg leading-tight font-semibold text-gray-900 hover:underline cursor-pointer">Finding connections to help decentralisation</a>
            </div>
          </div>
        </div>

      </div>




    </div >
  )
}

export default withTransition(Home)